name: Secrets example
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          if [ "$CANDY_SECURE" -eq "candy"]
          then
              echo "Got the secret"
          fi
        env: 
          CANDY_SECURE: ${{ secrets.CANY_APPLE_SECURE }}